name: knx_parser
description: A Dart library to parse KNX project files (.knxproj) from ETS5 and ETS6, including encrypted projects. Extracts data to JSON format.
version: 1.7.1
homepage: https://github.com/Nghi-NV/knx_parser
repository: https://github.com/Nghi-NV/knx_parser
issue_tracker: https://github.com/Nghi-NV/knx_parser/issues

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  archive: ^3.3.9
  xml: ^6.3.0
  crypto: ^3.0.3
  pointycastle: ^3.7.3

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.0
