name: knx_parser
description: A Dart library to parse KNX project files (.knxproj) from ETS5 and ETS6, including encrypted projects. Extracts data to JSON format.
version: 1.5.0
homepage: https://github.com/Nghi-NV/knx_parser
repository: https://github.com/Nghi-NV/knx_parser
issue_tracker: https://github.com/Nghi-NV/knx_parser/issues

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  archive: ^3.6.1
  xml: ^6.5.0
  crypto: ^3.0.3
  pointycastle: ^3.9.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
